<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <IsPackable>false</IsPackable>
	  <IsTestProject>true</IsTestProject>
	  <UseWPF>true</UseWPF>
	  <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="FluentAssertions" Version="8.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
	  <!-- Core xUnit v3 test framework -->
	<PackageReference Include="xunit.v3.core" Version="3.0.1" />
	<PackageReference Include="xunit.v3.assert" Version="3.0.1" />

	  <!-- Test runner for Visual Studio -->
	<PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>

	  <PackageReference Include="Xunit.StaFact" Version="3.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CollectaMundo\CollectaMundo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestResources\cardForeignData.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\cardIdentifiers.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\cardPrices.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\cards.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\cardForeignData.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\cardIdentifiers.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\cardPrices.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\cards.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\keyruneImages.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\myCollection.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\sets.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\tokenIdentifiers.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\tokens.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\CsvSeedTables\uniqueManaCostImages.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\keyruneImages.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\myCollection.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\sets.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\tokenIdentifiers.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\tokens.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\uniqueManaCostImages.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\view_allCards.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestResources\view_myCollection.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
